### ISSUE TITLE
[Question] Log to file example

### ISSUE THREAD

**Issue by mmenozzi** [amphp/log#2]
Hi, could you please add an example about logging to a file?

**Comment by mmenozzi** [comment]
Is it enough to replace `\STDOUT` with `fopen(‘/path/to/file’, ‘w’)`? Is it non-blocking this way?

**Comment by trowski** [comment]
Hi @mmenozzi!

No, `ResourceOutputStream` does not work in a non-blocking way with files. [`amphp/file`](https://github.com/amphp/file) is required for non-blocking file streams.  I added [an example logging to a file](https://github.com/amphp/log/blob/c8931ffa547ee0214ee32085b505ae39eacea958/examples/file-log.php). The file handle returned by `Amp\File\open()` implements `InputStream` and `OutputStream`, allowing files to be used in place of streams. So once a file is open, you can pass the file handle to `StreamHandler`.

**Comment by mmenozzi** [comment]
Ok thank you very much!
