### ISSUE TITLE
Problems with logging to console

### ISSUE THREAD

**Issue by prolic** [amphp/log#3]
```
Fatal error: Uncaught Amp\ByteStream\ClosedException: The stream is not writable in /var/www/vendor/amphp/byte-stream/lib/ResourceOutputStream.php:177
```

Happens usually at the end of a cli script, last debug message is lost and an exception thrown.

**Comment by kelunik** [comment]
This should be fine in the next version, because logging isn't async anymore then, which currently needs to happen due to the existing interface and lack of fibers.
